version: 2.1

jobs:
  build-and-test:
    working_directory: ~/app
    executor: python-default

    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            # Add any system dependencies your project needs

      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            python manage.py test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
