# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # Run Reactjs application
  start-reactjs:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: "Start Reactjs application"
          command: "npm start"

  # Run Python API
  run-python-api:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: "Run Python API"
          command: "python api.py"

  # Run Pytest cases
  run-pytest:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: "Run Pytest cases"
          command: "pytest"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-test-and-deploy-reactjs:
    jobs:
      - start-reactjs
      - run-python-api
      - run-pytest

# Run the build-test-and-deploy-reactjs workflow on every push to the master branch.
on:
  push:
    branches:
      - master
